# Generated by Django 2.1 on 2018-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapi', '0002_auto_20180820_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='source',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
