# Generated by Django 2.1 on 2018-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEnd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.PositiveIntegerField(unique=True)),
                ('call_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=11)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CallStart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.PositiveIntegerField(unique=True)),
                ('call_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=11)),
                ('destination', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(max_length=11)),
                ('period', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('records', models.CharField(max_length=1000)),
            ],
        ),
    ]
