# Generated by Django 2.1 on 2018-08-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callapi', '0005_auto_20180825_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='callapi.PhoneBill'),
        ),
        migrations.AlterField(
            model_name='phonebill',
            name='subscriber',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
