# Generated by Django 2.1 on 2018-08-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callapi', '0006_auto_20180825_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='callapi.PhoneBill'),
        ),
    ]
